#+Title: DML II - EDICIÓN DE DATOS


** Introducción
En este tema trataremos de crear, modificar y eliminar registros.

Recordad que el objetivo es tener un CRUD completo, esto es:
 - Create (~insert~ y/o ~replace~)
 - Read (~select~)
 - ~Update~
 - ~Delete~

Con un CRUD completo podremos gestionar cualquier conjunto de datos que requiera la empresa o servicio.

En este tema os tendréis que auto-documentar con las herramientas, referencias y enlaces que el profesor os ha ido facilitando a lo largo del curso.

** Utilidades
Como ya adelantamos, será de gran utilidad la creación de tablas temporales.

~CREATE TEMPORARY TABLE~ crea una tabla válida sólo para el usuario que la creó y en la sesión actual.

** Ejercicio:
1. Investiga como realizar un ~create~ de forma que:
   + Añade 1 empresa. Deberás tener en cuenta las restricciones impuestas (F.K.).
   + Añade 1 trabajadores a las tablas del tema 3. Deberás tener en cuenta las restricciones impuestas (F.K.).
   + Añade 2 contratos a dicho trabajador, uno de ellos sin fecha de finalización.
   + Añade o reemplaza si ya existe el trabajador con DNI ~87654321Z~.
   + Modifica el contrato sin fecha de finalización con fecha de 31 de julio de 2023.
   + Introduce un nuevo contrato y elimínalo.


** TRANSACTION - COMMIT y ROLLBACK

   Las transaciones es la técnica por lo que podemos realizar un conjunto de operaciones de forma atómica.

Para implementarla deberemos rodear las operaciones que deseemos "ATOMIZAR" entre un ~{ START TRANSACTION | BEGIN | BEGIN WORK }~ y un ~{ COMMIT | ROLLBACK }~.

Si todo sale correcto se consolidan las operaciones con un ~COMMIT~, y si algo no va bien (p.e. no tenemos saldo suficiente para comprar) se desacen todas las consultas con ~ROLLBACK~.

/Nota: ~START TRANSACTION~, ~BEGIN~ y ~BEGIN WORK~ son sinónimos que podremos utilizar indistintamente/.

   Deberemos haber indicado al sistema que vamos a utilizar transaciones mediante el ~SET autocommit = 0;~ o ~SET autocommit = OFF;~, ya que de otra forma MySQL toma por defecto el valor ~autocommit = 1~, y estar utilizando tablas que lo soporten, por ejemplo ~InnoDB~.

Para averiguar que tipo de tablas estamos utilizando, podemos utilizar: ~SHOW TABLE status from 00_db_Luis like 'P3_T%'\G;~, para tablas concretas, y  ~SELECT @@default_storage_engine;~, de forma global.

*** Ejercicio:
Vamos a probar el funcionamiento de las transacciones. Para vamos a utilizar la bd del tema 1 (concesionario de vehículos).
Los pasos serán:
1. Estableceremos la configuración que habilita las transacciones.
2. Indicaremos que comenzamos una transacción.
3. Consultaremos la tabla de contratos. Debe haber, y mostrar, 1 contrato.
4. Eliminaremos dicho contrato.
5. Consultaremos la tabla de contratos. Debe haber, y mostrar, 0 contratos.
6. Anularemos la transacción.
7. Consultaremos la tabla de contratos. Debe haber, y mostrar, 1 contrato. \\
/Nota:/ Si llegados a este punto no te muestra 1 contrato debes avisar al profesor.

También queremos el caso contrario, esto es, que completemos la transacción. Para ello:
1. Estableceremos la configuración que habilita las transacciones.
2. Indicaremos que comenzamos una transacción.
3. Consultaremos los clientes.
4. Daremos de alta un nuevo cliente de nombre 'Barry' y apellido 'Allen'
5. Consultaremos la tabla de clientes. Debe mostrarlo.
7. Confirmaremos la transacción.
8. Consultaremos la tabla clientes de nuevo. \\
/Nota:/ Si llegados a este punto no te muestra a 'Barry' debes avisar al profesor.

Y, también:
1. Estableceremos la configuración que habilita las transacciones.
2. Indicaremos que comenzamos una transacción.
3. Consultaremos la tabla de clientes y debe mostrar a 'Barry'
4. Modificaremos el nombre a 'Flash'
5. Consultaremos la tabla clientes y ahora deberá aparecer 'Flash Allen'.
6. Anularemos la transacción.
7. Consultaremos la tabla clientes y debe mostrar de nuevo a 'Barry Allen'. \\
/Nota:/ Si llegados a este punto no te muestra a 'Barry' debes avisar al profesor.

** Práctica:
Este tema no tiene práctica obligatoria, por lo que la evaluación será sólo vía exámen.
** Exámen:
Este tema tendrá exámen el próximo viernes 27 de enero.
